### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by cyang812** [cashwarden/docker#4]
执行 `docker-compose up -d` 后出错：

```
root@CY101:/mnt/c/Users/cyang/ubuntu/docker/cashwarden-docker# docker-compose up -d
Building api
Step 1/15 : FROM php:7.4.3-apache
 ---> d753d5b380a1
Step 2/15 : ARG TIMEZONE
 ---> Using cache
 ---> 2a41defdbce1
Step 3/15 : RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list     && sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list     && requirements="vim cron mariadb-client libwebp-dev libxpm-dev libmcrypt-dev libmcrypt4 libcurl3-dev libxml2-dev libmemcached-dev zlib1g-dev libc6 libstdc++6 libkrb5-3 openssl debconf libfreetype6-dev libjpeg-dev libtiff-dev libpng-dev git libmagickwand-dev ghostscript gsfonts libbz2-dev libonig-dev libzip-dev zip unzip"     && apt-get update && apt-get install -y --no-install-recommends $requirements && apt-get clean && rm -rf /var/lib/apt/lists/*     && docker-php-ext-install mysqli                               pdo_mysql                               gd
       exif                               bcmath                               opcache     && docker-php-ext-enable opcache
 ---> Using cache
 ---> 193dc9853b6a
Step 4/15 : RUN ln -snf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && echo ${TIMEZONE} > /etc/timezone     && printf '[PHP]\ndate.timezone = "%s"\n', ${TIMEZONE} > /usr/local/etc/php/conf.d/tzone.ini     && "date"
 ---> Using cache
 ---> 5059ae10b5ab
Step 5/15 : RUN a2enmod headers &&     a2enmod rewrite
 ---> Using cache
 ---> 41fa7306a96c
Step 6/15 : COPY --from=composer /usr/bin/composer /usr/bin/composer
 ---> Using cache
 ---> 57085ab7f596
Step 7/15 : RUN composer global require --optimize-autoloader         "fxp/composer-asset-plugin"         "hirak/prestissimo" &&     composer global dumpautoload --optimize &&     composer clear-cache
 ---> Running in 6b622d4a9f5d
Changed current directory to /root/.composer


  [RuntimeException]
  No composer.json present in the current directory, this may be the cause of the following exception.



  [Composer\Downloader\TransportException]
  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to repo.packagist.org:443


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

ERROR: Service 'api' failed to build: The command '/bin/sh -c composer global require --optimize-autoloader         "fxp/composer-asset-plugin"         "hirak/prestissimo" &&     composer global dumpautoload --optimize &&     composer clear-cache' returned a non-zero code: 1
```

**Comment by forecho** [comment]
https://github.com/cashwarden/api/commit/5e32cd60162b733adb6081df68bacac53872c773

更新代码，重试以下

**Comment by williezou** [comment]
执行 docker-compose up -d 后出错：
Building api
Step 1/14 : FROM php:7.4.3-apache
 ---> d753d5b380a1
Step 2/14 : ARG TIMEZONE
 ---> Using cache
 ---> fa5e27c4a316
Step 3/14 : RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list     && sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list     && requirements="vim cron mariadb-client libwebp-dev libxpm-dev libmcrypt-dev libmcrypt4 libcurl3-dev libxml2-dev libmemcached-dev zlib1g-dev libc6 libstdc++6 libkrb5-3 openssl debconf libfreetype6-dev libjpeg-dev libtiff-dev libpng-dev git libmagickwand-dev ghostscript gsfonts libbz2-dev libonig-dev libzip-dev zip unzip"     && apt-get update && apt-get install -y --no-install-recommends $requirements && apt-get clean && rm -rf /var/lib/apt/lists/*     && docker-php-ext-install mysqli                               pdo_mysql                               gd                                exif                               bcmath                               opcache     && docker-php-ext-enable opcache
 ---> Using cache
 ---> 10e8de3be90b
Step 4/14 : RUN ln -snf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && echo ${TIMEZONE} > /etc/timezone     && printf '[PHP]\ndate.timezone = "%s"\n', ${TIMEZONE} > /usr/local/etc/php/conf.d/tzone.ini     && "date"
 ---> Using cache
 ---> 483306f77fa9
Step 5/14 : RUN a2enmod headers &&     a2enmod rewrite
 ---> Using cache
 ---> 301cdd9db316
Step 6/14 : COPY --from=composer /usr/bin/composer /usr/bin/composer
ERROR: Service 'api' failed to build: Unknown flag: from
