### ISSUE TITLE
telegram_bot无法使用

### ISSUE THREAD

**Issue by lamysafari88** [cashwarden/docker#5]
RT.

已经配置好了：

```
TELEGRAM_BOT_NAME=
TELEGRAM_TOKEN=
```
运行`docker exec api php yii init/telegram` 时返回

```
Telegram set Webhook url success!
```

但是私聊自己的bot没反应..

**Comment by forecho** [comment]
https://github.com/cashwarden/docker/commit/8bcba6489c632a31cdc208038e4d9b5a15e177d8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R138
